#!/bin/bash

function portable_sed() {
    local pattern=$1
    local file=$2

    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        sed -i '' "$pattern" "$file"
    else
        # Linux and others
        sed -i "$pattern" "$file"
    fi
}

# Iterate over all directories
find . -type d | while read -r dir; do
    # if [ "$dir" = "." ]; then exit 1; fi

    dir_name=$(basename "${dir}")
    depth=$(echo "$dir" | tr -cd '/' | awk '{ print length }')
    # Check if the file exists
    if [ -f "${dir}/_index.md" ]; then
        echo "file exists ${dir_name}"
        # Use sed to replace {{title}} with the directory name
        portable_sed "s/{{title}}/$dir_name/g" "${dir}/_index.md"
        portable_sed "s/{{weight}}/$depth/g" "${dir}/_index.md"
        # rm "${dir}/_index.md"
    else
        if [ -f "${dir}/README.md" ]; then
            echo "moving readme to _index: ${dir_name}"
            cat ../_index.tpl.md > ${dir}/temp.txt
            cat ${dir}/README.md >> ${dir}/temp.txt
            cp ${dir}/temp.txt ${dir}/_index.md
            rm ${dir}/temp.txt
            rm ${dir}/README.md
        else
            echo "creating _index: ${dir_name}"
            # If the file doesn't exist, create it and populate with the directory name
            cp ../_index.tpl.md "${dir}/_index.md"
        fi

        portable_sed "s/{{title}}/$dir_name/g" "${dir}/_index.md"
        portable_sed "s/{{weight}}/$depth/g" "${dir}/_index.md"
    fi
done
